#!/bin/bash

# ------------------------------------------------------- #
#
# chinachu-api-get-top-reserve-time
# (Component of Chinachu with Mirakurun Sleep Script)
#
# Copyright (c) 2016 tag
#
# ------------------------------------------------------- #

# default values
DefaultChinachuHost="localhost"
DefaultChinachuPort="10772"

# funciton: Usage
function Usage() {
	echo "Usage: $0 [-h <host>] [-p <port>]"
	echo -e "host\tChinachu server's hostname (Defalut: ${DefaultChinachuHost})"
	echo -e "port\tChinachu server's port number (Defalut: ${DefaultChinachuPort})"
}

# analize options
while getopts :h:p: Opt
do
	case $Opt in
	h)
		ChinachuHost=$OPTARG
		;;
	p)
		ChinachuPort=$OPTARG
		;;
	\?)
		echo "Illegal option: $OPTARG"
		Usage
		exit 1
		;;
	esac
done

# set variables
ChinachuHost=${ChinachuHost:-${DefaultChinachuHost}}
ChinachuPort=${ChinachuPort:-${DefaultChinachuPort}}
ChinachuUrl="http://${ChinachuHost}:${ChinachuPort}"

ApiPath="/api/reserves.json"

# get the next recording begin time
RecTimeMsec=`curl -s ${ChinachuUrl}${ApiPath} | tr ',' '\n' | grep "start" | cut -d ":" -f 2 | sort | head -n 1`
if [ -n "${RecTimeMsec}" ]
then
	(( RecTime = ${RecTimeMsec} / 1000 ))
else
	RecTime=0
fi

echo $RecTime
