#!/bin/bash

# ------------------------------------------------------- #
#
# sleepcmd
# (Component of Chinachu with Mirakurun Sleep Script)
#
# Copyright (c) 2016-2017 tag
#
# ------------------------------------------------------- #

# ======================================================= #

# Include Chinachu Sleep Script configuration file
source /usr/local/etc/chinachu-mirakurun-ss/config

# ======================================================= #

echo "PowerManager: ${PowerManager}"
echo "PowerState: ${PowerState}"

case ${PowerManager} in
pm-utils)
        case ${PowerState} in
        hibernate)
                echo "[`date`] ${0}: System will go to hibernate soon."
                /usr/sbin/pm-hibernate
                ;;
        shutdown)
                echo "[`date`] ${0}: System will be shutdown soon."
                /usr/sbin/shutdown -h now
                ;;
        *)
                echo "[`date`] ${0}: error: please check \`PowerState' in config"
                ;;
        esac
        ;;
systemd)
        case ${PowerState} in
        hibernate)
                echo "[`date`] ${0}: System will go to hibernate soon."
                /usr/bin/systemctl hibernate
                ;;
        shutdown)
                echo "[`date`] ${0}: System will be shutdown soon."
                /usr/bin/systemctl shutdown
                ;;
        *)
                echo "[`date`] ${0}: error: please check \`PowerState' in config"
                ;;
        esac
        ;;
*)
	echo "[`date`] ${0}: error: please check \`PowerManager' in config"
        ;;
esac
